language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

before_install:
    script:
       - julia --project=. --color=yes -e 'using Pkg; Pkg.Registry.add("https://github.com/vincentcp/FrameFunRegistry");'

notifications:
  email: false

codecov: true
coveralls: true
